CREATE ROLE app_user WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1;

  CREATE DATABASE app
    WITH 
    OWNER = app_user
    ENCODING = 'UTF8'
    CONNECTION LIMIT = 10;

GRANT ALL ON DATABASE app TO app_user;

CREATE SCHEMA first_application
    AUTHORIZATION app_user;

GRANT ALL ON SCHEMA first_application TO app_user;