
GET http://localhost:3000/user/cd3b03ff33e76abd HTTP/1.1

###

POST  http://localhost:3000/user HTTP/1.1
content-type: application/json

{
  "email": "kler@gmail.com",
  "firstName": "ddfdfd",
  "lastName": "Shker"
}

###

PATCH http://localhost:3000/user/cd3b03ff33e76abd HTTP/1.1
content-type: application/json

{
  "profilePicture": "https://i.stack.imgur.com/Bb6z1.jpg?s=64&g=1"
}

###

DELETE http://localhost:3000/user/908cfe5493dd668b HTTP/1.1

###