
GET http://localhost:3000/user/ae6259ec9350137a HTTP/1.1

###

POST  http://localhost:3000/user HTTP/1.1
content-type: application/json

{
  "email": "abcd@gmail.com",
  "firstName": "ddfdfd",
  "lastName": "Shker"
}

###

PATCH http://localhost:3000/user/be7d2dfec48c6091 HTTP/1.1
content-type: application/json

{
  "firstName": "YAki",
  "profilePicture": "https://i.stack.imgur.com/Bb6z1.jpg?s=64&g=1"
}

###

DELETE http://localhost:3000/user/be7d2dfec48c6091 HTTP/1.1

###